const { ROLES } = require("./roles");

const PERMISSIONS = Object.freeze({
  MANAGE_USERS: "manage_users",
  VIEW_USERS: "view_users",
  MANAGE_ASSESSMENTS: "manage_assessments",
  MANAGE_FORMULAS: "manage_formulas",
  VIEW_FORMULAS: "view_formulas",
  VIEW_RESULTS: "view_results",
  VIEW_ANALYTICS: "view_analytics",
  VIEW_AUDIT_LOGS: "view_audit_logs",
});

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.MANAGE_ASSESSMENTS,
    PERMISSIONS.MANAGE_FORMULAS,
    PERMISSIONS.VIEW_FORMULAS,
    PERMISSIONS.VIEW_RESULTS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.MANAGE_ASSESSMENTS,
    PERMISSIONS.VIEW_FORMULAS,
    PERMISSIONS.VIEW_RESULTS,
    PERMISSIONS.VIEW_ANALYTICS,
  ],
  [ROLES.ASSESSMENT_MANAGER]: [PERMISSIONS.MANAGE_ASSESSMENTS, PERMISSIONS.VIEW_RESULTS],
  [ROLES.REVIEWER]: [PERMISSIONS.VIEW_RESULTS],
  [ROLES.VIEWER]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_FORMULAS,
    PERMISSIONS.VIEW_RESULTS,
    PERMISSIONS.VIEW_ANALYTICS,
  ],
});

module.exports = { PERMISSIONS, ROLE_PERMISSIONS };
